language: ruby

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - 2.0.0
  - rbx-2
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head

before_install:
  - gem update --remote bundler
  - gem update --system

sudo: false

bundler_args: --without=guard

notifications:
  disabled: true

script:
  - bundle exec rake
